// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCcPLejtlvFDedVy7xB5x9Xi2w7uc3eQ',
    appId: '1:354342243369:web:37521d744d5f5fe3c7e038',
    messagingSenderId: '354342243369',
    projectId: 'kidcare-87b44',
    authDomain: 'kidcare-87b44.firebaseapp.com',
    storageBucket: 'kidcare-87b44.firebasestorage.app',
    measurementId: 'G-JM0828PPNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4yW0ADitXP4CJIV5n9UFxb3DcdLvfMIc',
    appId: '1:354342243369:android:2a58cf13f4908547c7e038',
    messagingSenderId: '354342243369',
    projectId: 'kidcare-87b44',
    storageBucket: 'kidcare-87b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMbgaxVfCHwX-TidaJhs32mWx3WJuQLXI',
    appId: '1:354342243369:ios:ac96f72db86ded86c7e038',
    messagingSenderId: '354342243369',
    projectId: 'kidcare-87b44',
    storageBucket: 'kidcare-87b44.firebasestorage.app',
    iosBundleId: 'com.example.kidcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMbgaxVfCHwX-TidaJhs32mWx3WJuQLXI',
    appId: '1:354342243369:ios:ac96f72db86ded86c7e038',
    messagingSenderId: '354342243369',
    projectId: 'kidcare-87b44',
    storageBucket: 'kidcare-87b44.firebasestorage.app',
    iosBundleId: 'com.example.kidcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCcPLejtlvFDedVy7xB5x9Xi2w7uc3eQ',
    appId: '1:354342243369:web:a7e941efa0aa466fc7e038',
    messagingSenderId: '354342243369',
    projectId: 'kidcare-87b44',
    authDomain: 'kidcare-87b44.firebaseapp.com',
    storageBucket: 'kidcare-87b44.firebasestorage.app',
    measurementId: 'G-DGBGXM5QBT',
  );
}
